### ISSUE TITLE
Probleme de réponse serveur

### ISSUE THREAD

**Issue by titaniteChuck** [m2cci-TDP/TpReseaux4#8]
1) Client se connecte
2) echange serveur/client pour le pseudo 
3) premier echange:
     3.a) Serveur envoie "Votre message"
     3.b) Client envoie: "msg1"
     3.c) Serveur recoit "msg1", renvoie "msg1" 
     3.d) Client voit son message sur le chat
4) Deuxième echange
    4.a) Serveur envoie <rien>    <!------------- Pas de "Votre message:"
    4.b) Client envoie (quand meme) "msg2"
    4.c) Serveur recoit "msg2", renvoie "Votre message"
    4.d) Client ne voit pas son message "msg2", mais voit "Votre message" du serveur
5) Troisieme echange, 
    5.a) client envoie "msg3"
    5.b) serveur recoit "msg3"
    5.c) serveur ne renvoit pas "votre message" (idem quen 4) ) 
    5.d) Cette fois-ci, le client ne recoit pas le message qu'il vient d'envoyer, "msg3", mais "msg2" !!! 
(qui doit etre en attente quelque part?)

Votre mission si vous l'acceptez, faites lui les fesses !!!!

**Comment by titaniteChuck** [comment]
a partir de là, on a un décalage coté réponse serveur: une fois "Votre message" une fois rien. Et coté client, a chaque répétition de 4) et 5) on a un décalage en plus, genre si on continue avec "msg4" et "msg5", "msg4" mene à aucune sortie (vu en 4), et lors de l'envoi de "msg5" le client affichera "msg3", etc etc

**Comment by theo-dep** [comment]
solve : 1 readPrint(socket); en trop qui était bloquant !
